version: '3.3'

services:
  redis_server:
    container_name: redis_server
    image: redis
    ports:
      - "6379:6379"
  backend_server:
    container_name: backend_prueba
    build: ./back-end
    ports: 
      - "3050:3000"
    depends_on: 
      - redis_server
    environment: 
      - NODE_ENV=prod
  frontend_server:
    container_name: frontend_prueba
    build: ./front-end
    ports:
      - "8080:80"
